//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pmis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pmis.sangah.com")]
        public string pmis_api_url {
            get {
                return ((string)(this["pmis_api_url"]));
            }
            set {
                this["pmis_api_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GLB_PMIS")]
        public string pmis_project_code {
            get {
                return ((string)(this["pmis_project_code"]));
            }
            set {
                this["pmis_project_code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pmis_auth_key {
            get {
                return ((string)(this["pmis_auth_key"]));
            }
            set {
                this["pmis_auth_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>공통</string>
  <string>건축</string>
  <string>기계</string>
  <string>토목</string>
  <string>조경</string>
  <string>전기</string>
  <string>통신</string>
  <string>기타</string>
  <string>소방</string>
  <string>관급자재</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection register_discipline {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_discipline"]));
            }
            set {
                this["register_discipline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>승인용</string>
  <string>공사용</string>
  <string>최종용</string>
  <string>참고용</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection register_status {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_status"]));
            }
            set {
                this["register_status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>공문서 &gt; 문서송부전</string>
  <string>문서 및 도면 &gt; co-operation &gt; 공문서관리 &gt; CM-설계</string>
  <string>문서 및 도면 &gt; co-operation &gt; 공문서관리 &gt; CM-설계 &gt; CM</string>
  <string>문서 및 도면 &gt; co-operation &gt; 공문서관리 &gt; CM-시공</string>
  <string>문서 및 도면 &gt; co-operation &gt; 공문서관리 &gt; CM-시공 &gt; CM</string>
  <string>문서 및 도면 &gt; co-operation &gt; 공문서관리 &gt; CM-시공 &gt; 시공</string>
  <string>문서 및 도면 &gt; co-operation &gt; 공문서관리 &gt; 발주처-CM</string>
  <string>문서 및 도면 &gt; co-operation &gt; 공문서관리 &gt; 발주처-CM &gt; CM</string>
  <string>문서 및 도면 &gt; co-operation &gt; 공문서관리 &gt; 발주처-CM &gt; 발주처</string>
  <string>문서 및 도면 &gt; co-operation &gt; 회의자료</string>
  <string>문서 및 도면 &gt; 사업비/계약 &gt; 기성자료실</string>
  <string>문서 및 도면 &gt; 설계관리 &gt; VE자료실</string>
  <string>문서 및 도면 &gt; 설계관리 &gt; 도면 &gt; 기본도면/도서</string>
  <string>문서 및 도면 &gt; 설계관리 &gt; 도면 &gt; 시공도면/도서</string>
  <string>문서 및 도면 &gt; 설계관리 &gt; 설계보고 &gt; 설계단계 CM 월간보고</string>
  <string>문서 및 도면 &gt; 설계관리 &gt; 설계보고 &gt; 설계단계 CM 일일보고</string>
  <string>문서 및 도면 &gt; 설계관리 &gt; 설계보고 &gt; 설계단계 CM 주간보고</string>
  <string>문서 및 도면 &gt; 시공관리 &gt; 감리/CM일지</string>
  <string>문서 및 도면 &gt; 시공관리 &gt; 감리주간보고</string>
  <string>문서 및 도면 &gt; 시공관리 &gt; 시공일일보고</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection register_type {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_type"]));
            }
            set {
                this["register_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("register")]
        public string register_folder_uri {
            get {
                return ((string)(this["register_folder_uri"]));
            }
            set {
                this["register_folder_uri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data/archive.db")]
        public string sqlite_db_location {
            get {
                return ((string)(this["sqlite_db_location"]));
            }
            set {
                this["sqlite_db_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sqlite")]
        public string db_type {
            get {
                return ((string)(this["db_type"]));
            }
            set {
                this["db_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ko_KR")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pictures")]
        public string picture_folder_uri {
            get {
                return ((string)(this["picture_folder_uri"]));
            }
            set {
                this["picture_folder_uri"] = value;
            }
        }
    }
}
