//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pmis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pmis.sangah.com")]
        public string pmis_api_url {
            get {
                return ((string)(this["pmis_api_url"]));
            }
            set {
                this["pmis_api_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YNPOWER")]
        public string pmis_project_code {
            get {
                return ((string)(this["pmis_project_code"]));
            }
            set {
                this["pmis_project_code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pmis_auth_key {
            get {
                return ((string)(this["pmis_auth_key"]));
            }
            set {
                this["pmis_auth_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>일반</string>
  <string>건축</string>
  <string>구조</string>
  <string>토목</string>
  <string>조경</string>
  <string>기계</string>
  <string>전기</string>
  <string>통신</string>
  <string>소방</string>
  <string>Other</string>
  <string>계측</string>
  <string>M</string>
  <string>P</string>
  <string>F</string>
  <string>H</string>
  <string>R</string>
  <string>J</string>
  <string>E</string>
  <string>C</string>
  <string>A</string>
  <string>S</string>
  <string>Q</string>
  <string>X</string>
  <string>T</string>
  <string>V</string>
  <string>공통</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection register_discipline {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_discipline"]));
            }
            set {
                this["register_discipline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>정보용</string>
  <string>공사용</string>
  <string>승인용</string>
  <string>폐기</string>
  <string>완료</string>
  <string>임시</string>
  <string>승인</string>
  <string>정보</string>
  <string>검토</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection register_status {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_status"]));
            }
            set {
                this["register_status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Document &amp; Drawing &gt; Commissioning Management &gt; 시운전 Report</stri" +
            "ng>\r\n  <string>Document &amp; Drawing &gt; Commissioning Management &gt; 시운전공정</" +
            "string>\r\n  <string>Document &amp; Drawing &gt; Commissioning Management &gt; 시운전" +
            "미비사항</string>\r\n  <string>Document &amp; Drawing &gt; Commissioning Management &g" +
            "t; 시운전표</string>\r\n  <string>Document &amp; Drawing &gt; Construction Management " +
            "&gt; Construction daily report</string>\r\n  <string>PMIS Data Management &gt; Dat" +
            "a Management(영남화력) &gt; 공급자 송부전</string>\r\n  <string>PMIS Data Management &gt; Da" +
            "ta Management(영남화력) &gt; 공급자 송부전 &gt; 6BOP</string>\r\n  <string>PMIS Data Managem" +
            "ent &gt; Data Management(영남화력) &gt; 공급자 송부전 &gt; MHPS</string>\r\n  <string>PMIS D" +
            "ata Management &gt; Data Management(영남화력) &gt; 공급자 송부전 &gt; 대우건설</string>\r\n  <st" +
            "ring>PMIS Data Management &gt; Data Management(영남화력) &gt; 공급자 송부전 &gt; 포스코건설</st" +
            "ring>\r\n  <string>PMIS Data Management &gt; Data Management(영남화력) &gt; 기타자료실</str" +
            "ing>\r\n  <string>PMIS Data Management &gt; Data Management(영남화력) &gt; 기타자료실 &gt; " +
            "발주처 자료</string>\r\n  <string>PMIS Data Management &gt; Data Management(영남화력) &gt; " +
            "안전자료실</string>\r\n  <string>PMIS Data Management &gt; Data Management(영남화력) &gt; 안" +
            "전지적서</string>\r\n  <string>PMIS Data Management &gt; Data Management(영남화력) &gt; 자료" +
            "관리 &gt; A/E자료실</string>\r\n  <string>PMIS Data Management &gt; Data Management(영남화" +
            "력) &gt; 자료관리 &gt; A/E자료실 &gt; A/E문서</string>\r\n  <string>PMIS Data Management &gt" +
            "; Data Management(영남화력) &gt; 자료관리 &gt; 공급자자료실(보조기기) &gt; 6.9kv 고압차단기반(SWGR)</str" +
            "ing>\r\n  <string>PMIS Data Management &gt; Data Management(영남화력) &gt; 자료관리 &gt; 공" +
            "급자자료실(보조기기) &gt; 6.9kv 고압차단기반(SWGR) &gt; 비츠로 테크</string>\r\n  <string>PMIS Data Ma" +
            "nagement &gt; Data Management(영남화력) &gt; 자료관리 &gt; 공급자자료실(보조기기) &gt; ECMS(전기설비 감" +
            "시 제어반) &gt; 회송송부전</string>\r\n  <string>PMIS Data Management &gt; Data Management(" +
            "영남화력) &gt; 자료관리 &gt; 공급자자료실(보조기기) &gt; ECMS(전기설비 감시 제어반) &gt; 효성</string>\r\n  <st" +
            "ring>PMIS Data Management &gt; Data Management(영남화력) &gt; 자료관리 &gt; 공급자자료실(보조기기)" +
            " &gt; 수폐수처리설비</string>\r\n  <string>PMIS Data Management &gt; Data Management(영남화력" +
            ") &gt; 자료관리 &gt; 공급자자료실(보조기기) &gt; 수폐수처리설비 &gt; 휴비스워터</string>\r\n  <string>PMIS D" +
            "ata Management &gt; Data Management(영남화력) &gt; 자료관리 &gt; 공급자자료실(보조기기) &gt; 영남복합 " +
            "순환수펌프 구매</string>\r\n  <string>PMIS Data Management &gt; Data Management(영남화력) &gt" +
            "; 자료관리 &gt; 공급자자료실(보조기기) &gt; 영남복합 순환수펌프 구매 &gt; 신신기계</string>\r\n  <string>PMIS D" +
            "ata Management &gt; Data Management(영남화력) &gt; 자료관리 &gt; 공급자자료실(보조기기) &gt; 영남천연가" +
            "스 발전소 건설 크레인 구매 &gt; 고려호이스트</string>\r\n  <string>PMIS Data Management &gt; Data M" +
            "anagement(영남화력) &gt; 자료관리 &gt; 공급자자료실(보조기기) &gt; 전력용변압기</string>\r\n  <string>PMIS" +
            " Data Management &gt; Data Management(영남화력) &gt; 자료관리 &gt; 공급자자료실(보조기기) &gt; 전력용" +
            "변압기 &gt; 회송송부전</string>\r\n  <string>PMIS Data Management &gt; Data Management(영남화" +
            "력) &gt; 자료관리 &gt; 공급자자료실(보조기기) &gt; 전력용변압기 &gt; 효성</string>\r\n  <string>PMIS Data" +
            " Management &gt; Data Management(영남화력) &gt; 자료관리 &gt; 공급자자료실(주기기)</string>\r\n  <s" +
            "tring>PMIS Data Management &gt; Data Management(영남화력) &gt; 자료관리 &gt; 공급자자료실(주기기)" +
            " &gt; MHPS</string>\r\n  <string>PMIS Data Management &gt; Data Management(영남화력) &" +
            "gt; 자료관리 &gt; 공급자자료실(주기기) &gt; 대우건설</string>\r\n  <string>PMIS Data Management &gt" +
            "; Data Management(영남화력) &gt; 자료관리 &gt; 지입자재</string>\r\n  <string>PMIS Data Manage" +
            "ment &gt; Data Management(영남화력) &gt; 자료관리 &gt; 지입자재 &gt; 기계</string>\r\n  <string>" +
            "PMIS Data Management &gt; Data Management(영남화력) &gt; 품질자료실</string>\r\n  <string>P" +
            "MIS Data Management &gt; Data Management(영남화력) &gt; 품질자료실 &gt; 품질협의체</string>\r\n " +
            " <string>PMIS Data Management &gt; Data Management(영남화력) &gt; 품질절차서 &gt; 절차서 &gt" +
            "; 안전절차서</string>\r\n  <string>PMIS Data Management &gt; Data Management(영남화력) &gt;" +
            " 품질절차서 &gt; 절차서 &gt; 작업절차서</string>\r\n  <string>PMIS Data Management &gt; Data Ma" +
            "nagement(영남화력) &gt; 품질절차서 &gt; 절차서 &gt; 품질절차서</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection register_type {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_type"]));
            }
            set {
                this["register_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("register")]
        public string register_folder_uri {
            get {
                return ((string)(this["register_folder_uri"]));
            }
            set {
                this["register_folder_uri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data/ypower.db")]
        public string sqlite_db_location {
            get {
                return ((string)(this["sqlite_db_location"]));
            }
            set {
                this["sqlite_db_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sqlite")]
        public string db_type {
            get {
                return ((string)(this["db_type"]));
            }
            set {
                this["db_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ko_KR")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pictures")]
        public string picture_folder_uri {
            get {
                return ((string)(this["picture_folder_uri"]));
            }
            set {
                this["picture_folder_uri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string current_profile {
            get {
                return ((string)(this["current_profile"]));
            }
            set {
                this["current_profile"] = value;
            }
        }
    }
}
